language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.2
matrix:
  allow_failures:
  - rvm: jruby-9.2
  fast_finish: true
before_install:
  - gem install bundler
  - bundle --version
  - git --version
